name: Tests

on:
  push:
    branches: [ master, main ]
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install Dependencies
        run: pip install black snakefmt

      - name: Run Linter
        run: |
          black --check .
          snakefmt --check *.smk

  test-unit:
    name: Run Extension Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
            python-version: 3.12
      
      - name: Install Dependencies
        run: pip install pytest

      - name: Run Unit Tests
        run: true #pytest .tests/unit/
        # This'll require having a lib within scripts with internal tests

  test-e2e:
    name: Test Extension with Sunbeam
    runs-on: ubuntu-latest
    needs:
      - test-unit
      - lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Test with Sunbeam
        uses: sunbeam-labs/sbx_test_action@v1

      #- name: Dump Logs
      #  shell: bash
      #  if: always()
      #  run: tail -n +1 logs/*
      
      #- name: Dump Stats
      #  shell: bash
      #  if: always()
      #  run: cat stats/*
